basePath: /
host: aqueous-spire-56268.herokuapp.com
info:
  contact: {email: me@justincovell.net, name: Justin Covell, url: 'https://justincovell.net'}
  description: An API to send SMS using bitcoin.
  license: {name: MIT LICENSE, url: 'https://opensource.org/licenses/MIT'}
  termsOfService: https://opensource.org/licenses/MIT
  title: 21 SMS
  version: '0.1'
  x-21-app-image: https://cdn.filepicker.io/api/file/PUU3Sjy3QUibbOY7sRoi
  x-21-category: utilities
  x-21-keywords: [sms, phone, text]
  x-21-quick-buy: '$ 21 buy https://aqueous-spire-56268.herokuapp.com/buy --data ''{"phone":
    "123-456-7890", "text": "I bought this text with Bitcoin!"}''


    # Output

    # {

    #     "from": "+14433455051",

    #     "message": "I bought this text with Bitcoin!",

    #     "to": "+11234567890"

    # }

    '
  x-21-total-price: {max: 2500, min: 2500}
  x-21-usage: ''
paths:
  /buy:
    post:
      produces: [text/plain]
      responses:
        200:
          description: a message send confirmation
          schema: {type: text}
      summary: send a text message to a given phone number
schemes: [https]
swagger: '2.0'
x-21-manifest-path: /manifest
